services:
  - type: web
    name: spring-boot-app
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
    autoDeploy: true
