services:
  - type: web
    name: spring-boot-app
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 21
    autoDeploy: true

